# Generated by Django 5.1.5 on 2025-01-15 22:48

from django.db import migrations

def forward_func(apps, schema_editor):
    user_model = apps.get_model('auth', 'User')
    invoice_model = apps.get_model('invoices', 'Invoice')
    invoice_item_model = apps.get_model('invoices', 'InvoiceItem')
    
    admin_user = user_model.objects.create_superuser(
        username='admin', is_staff=True, password='admin')

    
    invoice = invoice_model.objects.create(
        number='001',
        date='2025-01-15',
        customer='John Doe',
        paid=False,
    )
    
    
    
    invoice_item_model.objects.create(
        invoice=invoice,
        description='Item 1',
        quantity=2,
        price=1000,
    )
    
    invoice_item_model.objects.create(
        invoice=invoice,
        description='Item 2',
        quantity=5,
        price=500,
    )
    
    invoice_item_model.objects.create(
        invoice=invoice,
        description='Item 3',
        quantity=1,
        price=100,
    )
    
    invoice_item_model.objects.create(
        invoice=invoice,
        description='Item 4',
        quantity=0,
        price=100,
    )
    
    
def reverse_func(apps, schema_editor):
    invoice_model = apps.get_model('invoices', 'Invoice')
    invoice_item_model = apps.get_model('invoices', 'InvoiceItem')
    users_model = apps.get_model('auth', 'User')
    
    users_model.objects.all().delete()
    invoice_item_model.objects.all().delete()
    invoice_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]