# Generated by Django 5.1.5 on 2025-01-17 04:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='withholding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
    ]
