# Generated by Django 5.1.5 on 2025-01-16 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='withholding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
